### ISSUE TITLE
Android - CookieManager.set()

### ISSUE THREAD

**Issue by songzhw** [react-native-community/cookies#54] opened 2020-06-03 14:08 UTC
# Feature request

Right now the CookieManager.set() is only for iOS. Android actually need it as well.

## Why it is needed
There are scenarios that Android need to set Cookie that is not from response

## Possible implementation
Android has a system class, `CookieManager`, which support `setCookie(url, cookieValue)`

### Code sample

```
CookieManager.set({
  name: 'myCookie',
  value: 'myValue',
  domain: 'some domain',
  origin: 'some origin',
  path: '/',
  version: '1',
  expiration: '2015-05-30T12:30:00.00-05:00'
}).then((res) => {
  console.log('CookieManager.set =>', res);
});```

**Comment by StagasaurusRex** [comment] 2020-06-04 17:09
This is a duplicate of #25 and work is basically completed in PR #45

**Comment by songzhw** [comment] 2020-06-05 12:50
> This is a duplicate of #25 and work is basically completed in PR #45

Sound great. Is it gonna be released in the next version?

**Comment by YoliFD** [comment] 2020-06-08 17:36
Yes, looking to get this released in the next version.

**Comment by songzhw** [comment] 2020-06-17 21:06
> Yes, looking to get this released in the next version.

Thanks for replying. Do we have a date the next version release?

**Comment by songzhw** [comment] 2020-06-17 21:13
> Yes, looking to get this released in the next version.

Thank you~

**Closed** 2020-06-17 21:13 UTC
